### ISSUE TITLE
登入系統實作

### ISSUE THREAD

**Issue by awchjimmy** [awchjimmy/ionfire-template#2]
- [x] 資料表規劃

### 本地端
- [ ] 帳號登入
- [ ] 帳號註冊

### 第三方
- [x] Google 登入
- [x] Google 註冊
- [ ] Facebook 登入
- [ ] Facebook 註冊
- [ ] Line 登入
- [ ] Line 註冊

### JWT-based Login
- [x] 產生token (jsonwebtoken)
- [x] 驗證token (express-jwt)
- [x] ionic localStorage
- [x] ionic interceptor

**Comment by awchjimmy** [comment]
```yaml
profile:
  c9da9bfb97fd:
    name: Lauren Ramos
    email: lauren.ramos58@example.com
    phone: (336)-444-8201
    picture: https://randomuser.me/api/portraits/women/56.jpg
  2bb4d79afee5:
    name: Evie Patel
    email: evie.patel@example.com
    phone: (466)-999-3087
    picture: https://randomuser.me/api/portraits/thumb/women/82.jpg
```

```yaml
accounts:
  gl-c3feb8887abed9ec1561b9aa2c9f58de21d1d3d9: c9da9bfb97fd
  gl-9e0c9740eebca9a21444833ae580fcaf9d1dfd22: 2bb4d79afee5
```
